[package]
name = "xiao-esp32s3-camera"
version = "0.1.0"
edition = "2021"
resolver = "2"
rust-version = "1.82"

[[bin]]
name = "xiao-esp32s3-camera"
harness = false

[profile.release]
opt-level = "s"

[profile.dev]
debug = true
opt-level = "z"

[dependencies]
anyhow = "1"
embedded-svc = "0.29"
esp-idf-svc = "0.52.1"
log = "0.4"

[build-dependencies]
embuild = "0.33"

[[package.metadata.esp-idf-sys.extra_components]]
remote_component = { name = "espressif/esp32-camera", version = "2.1.7" }

[[package.metadata.esp-idf-sys.extra_components]]
component_dirs = ["camera_bridge"]
bindings_header = "camera_bridge/include/camera_bridge.h"
bindings_module = "camera"
